### PR TITLE
Added Map Action Type

### LINKED ISSUE #24: Add support for Map Action Type
Sub-issue for #22 

**Current Behavior**
Map is not shown to the user for Map ActionType in Answer.

**Expected Behavior**
The map must be shown.

### PR DESCRIPTION
**Pull request by betterclever**
Fixes #24 

Added Map Action Type with Leaflet Map Module

Screenshots:

screenshot from 2017-07-16 03-07-53

### CODE REVIEW

**Comment by betterclever** [comment]
@chashmeetsingh @AliAyub007 @rishiraj824 @DravitLochan @chiragw15 @mayank408 @dynamitechetan Please review

**Review by DravitLochan — APPROVED** [review]

**Review by chashmeetsingh — COMMENTED** [review]
We need to add a marker in the map view as well.

**Review by dynamitechetan — COMMENTED** [review]
Try to remove the link of the open street maps. I think its not required here.

**Comment by chashmeetsingh** [comment]
@dynamitechetan I suppose a better option would be to remove the link from the answer action since that's already present in the anchor action. What do you think?

**Comment by betterclever** [comment]
@chashmeetsingh is right. This information is contained in both answer and anchor action type and is redundant. I will remove it manually for now but a better option is to remove this link in answer action from the server. 
@dynamitechetan What do you think?

**Comment by betterclever** [comment]
Apparantly, SUSI Server is not replying with Map Type Response at the moment for queries like "Where is Singapore?" http://api.susi.ai/susi/chat.json?timezoneOffset=-330&q=where+is+Singapore%3F  I have made suggested changes but cannot test at the moment. I will update the PR soon

**Comment by betterclever** [comment]
screenshot from 2017-07-18 16-48-01

@chashmeetsingh @dynamitechetan Made suggested changes. Please review.

**Review by chashmeetsingh — APPROVED** [review]

**Review by AliAyub007 — APPROVED** [review]

**Pull request merged**
