### PR TITLE
Added Table Action Type support

### LINKED ISSUE #36: Add Table Action Type
Subissue for #22 
Support for Table Action Type for queries like ```universities in germany``` is not present yet. It needs to be added.

### PR DESCRIPTION
**Pull request by betterclever**
Fixes #36 : Add Table Action Type Support

**Screenshots**

screenshot from 2017-07-31 20-33-04

### CODE REVIEW

**Comment by betterclever** [comment]
@rishiraj824 @uday96 @madhavrathi @isuruAb Please review

**Review by rishiraj824 — COMMENTED** [review]
@betterclever try aligning the text to the left instead of center.

**Comment by madhavrathi** [comment]
@betterclever consider Rishi's comment. Rest looks good to me .
Thanks

**Comment by betterclever** [comment]
screenshot from 2017-07-31 22-25-26

@rishiraj824 Is it fine now?

**Review by rishiraj824 — APPROVED** [review]
LGTM :+1:

**Review by madhavrathi — APPROVED** [review]

**Pull request merged**
